--------------------------------------------------------
--  DDL for Table CIDADES
--------------------------------------------------------

  CREATE TABLE "GITDB"."CIDADES" 
   (	"COD_CIDADE" VARCHAR2(7 BYTE), 
	"COD_UF" VARCHAR2(2 BYTE), 
	"NOME_CIDADE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TBS" ;
