--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "GITDB"."CLIENTES" ADD CONSTRAINT "CK_TC1" CHECK (TIPO_CLIENTE in ('F', 'J')) ENABLE;
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("COD_EMPRESA" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("RAZAO_CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("FANTASIA" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("ENDERECO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("NRO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("BAIRRO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("COD_CIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."CLIENTES" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TBS"  ENABLE;
