--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "GITDB"."CLIENTES" 
   (	"COD_EMPRESA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"RAZAO_CLIENTE" VARCHAR2(100 BYTE), 
	"FANTASIA" VARCHAR2(15 BYTE), 
	"ENDERECO" VARCHAR2(50 BYTE), 
	"NRO" VARCHAR2(10 BYTE), 
	"BAIRRO" VARCHAR2(20 BYTE), 
	"COD_CIDADE" VARCHAR2(7 BYTE), 
	"CEP" VARCHAR2(8 BYTE), 
	"CNPJ_CPF" VARCHAR2(15 BYTE), 
	"TIPO_CLIENTE" CHAR(1 BYTE), 
	"DATA_CADASTRO" DATE, 
	"COD_PAGTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TBS" ;
