--------------------------------------------------------
--  Constraints for Table FORNECEDORES
--------------------------------------------------------

  ALTER TABLE "GITDB"."FORNECEDORES" ADD CONSTRAINT "CK_TF1" CHECK (TIPO_FORNEC in ('F', 'J')) ENABLE;
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("COD_EMPRESA" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("ID_FOR" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("RAZAO_FORNEC" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("FANTASIA" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("ENDERECO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("NRO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("BAIRRO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("COD_CIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "GITDB"."FORNECEDORES" ADD PRIMARY KEY ("ID_FOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TBS"  ENABLE;
